---
- name: Update APT Cache
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  become: true
  apt:
    name:
      - curl
      - tree
      - vim
      - tmux
      - jq
    state: present

- name: Setup vimrc
  copy:
    src: "vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"

- name: Setup tmux
  copy:
    src: "tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"