---
- name: Download CLI
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: "{{ ansible_user_dir }}/awscliv2.zip"

- name: Unzip CLI
  unarchive:
    src: "{{ ansible_user_dir }}/awscliv2.zip"
    dest: "{{ ansible_user_dir }}"

- name: Install CLI
  become: true
  shell: "./aws/install"
  args:
    chdir: "{{ ansible_user_dir }}"
    creates: "/usr/local/bin/aws"