---
- name: Check required vars
  assert:
    that:
      - "git_user is defined"
      - "git_email is defined"

- name: Install Git
  become: yes
  apt:
    name: git
    state: present

- name: Configure Git
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - { name: 'init.defaultBranch', value: "{{ git_default_branch }}"}
    - { name: 'user.name', value: "{{ git_user }}" }
    - { name: 'user.email', value: "{{ git_email }}"}
    - { name: 'credential.helper', value: "cache --timeout=36000"}
    - { name: 'alias.lg', value: 'log --oneline --decorate --graph'}
    - { name: 'alias.l', value: 'log --oneline'}
    - { name: 'alias.s', value: 'status -s'}
    - { name: 'alias.co', value: 'checkout'}