---
- name: Install Pip
  become: true
  apt:
    name: python3-pip
    state: present

- name: Install localstack pip module
  ansible.builtin.pip:
    name: localstack

- name: Install awslocal pip module
  ansible.builtin.pip:
    name: awscli-local

- name: Install tflocal pip module
  ansible.builtin.pip:
    name: terraform-local