---
- name: Install required apt packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add Apt Key
  become: true
  get_url:
    url: "{{ docker_apt_gpg_key }}"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true

- name: Add Apt Repository
  become: true
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    update_cache: true
    state: present

- name: Install Docker
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin

- name: Add current user to docker group
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    groups: "docker"
    append: yes